version: '2'
services:
  mongo:
    image: mongo:3.2
    networks:
      - pritunl
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - /opt/mongo/data:/data/db
  pritunl:
    build: .
    image: pritunl
    depends_on:
      - mongo
    networks:
      - pritunl
    ports:
      - "2020:80"
      - "443:443"
      - "1194/udp:1194/udp"
    privileged: true
    restart: always

networks:
  pritunl:
