apiVersion: v1
kind: Service
metadata:
  name: pritunl
  namespace: infrastructure
spec:
  type: LoadBalancer
  ports:
    - port: 1194
      name: openvpn
      protocol: "UDP"
  selector:
    app: pritunl

---
apiVersion: v1
kind: Service
metadata:
  name: pritunl-ui
  namespace: infrastructure
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: "TCP"
      targetPort: 80
      name: http
    - port: 443
      targetPort: 443
      protocol: "TCP"
      name: https
  selector:
    app: pritunl

