
version: '3'

services:
 jenkins:
  image: jenkinsci/jenkins:alpine
  container_name: jenkins
  network_mode: host
  restart: always
  ports:
    - "50000:50000"
    - "8080:8080"
  dns:
    - 10.30.198.198
    - 10.28.86.86
  dns_search:
    - oppd.oppd-ds.com
    - oppd.com
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /docker/data/jenkins/var:/var/lib/jenkins/
    - /docker/data/jenkins:/var/jenkins_home/
    - /etc/localtime:/etc/localtime:ro
    - /usr/bin/docker:/usr/bin/docker
  environment:
    JAVA_OPTS: "-Djava.awt.headless=true"
    NEXUS_PORT: 8082
    SONAR_PORT: 9000
    SONAR_DB_PORT: 5432
    SERVICE_8080_CHECK_HTTP: /
    SERVICE_8080_CHECK_INTERVAL: 10s
    SERVICE_8080_CHECK_TIMEOUT: 5s
    SERVICE_8080_NAME: jenkins
    SERVICE_8080_TAGS: urlprefix-jenkins.oppd.oppd-ds.com/

 nexus:
  build: ./nexus3
  container_name: nexus3
  restart: always
  ports:
    - "8082:8081"
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /docker/data/nexus:/opt/nexus/data
  environment:
    SERVICE_8081_CHECK_HTTP: /
    SERVICE_8081_CHECK_INTERVAL: 10s
    SERVICE_8081_CHECK_TIMEOUT: 5s
    SERVICE_8081_NAME: nexus
    SERVICE_8081_TAGS: urlprefix-nexus.oppd.oppd-ds.com/

# sonardb:
#  restart: always
#  image: postgres:9.6
#  container_name: sonardb
#  ports:
#    - "5432:5432"
#  environment:
#    POSTGRES_USER: sonar
#    POSTGRES_PASSWORD: sonar
#  volumes:
#    - /etc/localtime:/etc/localtime:ro
#
# sonar:
#  image: sonarqube:6.7.1-alpine
#  restart: always
#  container_name: sonar
#  ports:
#    - "9000:9000"
#    - "9092:9092"
#  depends_on:
#    - sonardb
#  environment:
#    SONARQUBE_JDBC_URL: jdbc:postgresql://sonardb:5432/sonar
#    SONARQUBE_JDBC_USERNAME: sonar
#    SONARQUBE_JDBC_PASSWORD: sonar
#    SERVICE_9000_CHECK_HTTP: "/"
#    SERVICE_9000_CHECK_INTERVAL: "10s"
#    SERVICE_9000_CHECK_TIMEOUT: "5s"
#  volumes:
#    - /etc/localtime:/etc/localtime:ro
#    - /docker/data/sonar:/opt/sonarqube/data
#

