---
- hosts: localhost
  sudo: true
  roles:
   - role: nagios
  tasks:
  - shell: sed -i 's/nagiosadmin/d5864,s6511,s6678,x5510,x7679,x8693,x11192,x15341/g' /etc/nagios/cgi.cfg
  - service: name=nagios state=restarted
  - yum: name=nagios-plugins-all state=present
